In [2]:
# ndArray 생성 실습(1/2)
import numpy as np
A = [1,2,5,0,3,0]

print(np.array(A))
print(np.array(A, dtype='float32'))
print(np.array(A, dtype= 'bool'))

[1 2 5 0 3 0]
[1. 2. 5. 0. 3. 0.]
[ True  True  True False  True False]


In [4]:
#ndArray 생성 실습 (2/2) 함수를 사용한 생성

import numpy as np
print(np.zeros((3,2)))
print(np.ones((1)))
print(np.arange(1,10,2))
print(np.linspace(1,10,5))
print(np.random.random((2,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1.]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[0.04674299 0.89401475]
 [0.19752979 0.51104503]]


In [7]:
# 유니버설 함수 실습
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([0,1,0,1,0])

print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(y/x)
print(x ** y)

[1 2 3 4 5]
[0 1 0 1 0]
[1 3 3 5 5]
[1 1 3 3 5]
[0 2 0 4 0]
[0.   0.5  0.   0.25 0.  ]
[1 2 1 4 1]


In [13]:
#표준화 (배열의 규모를 일정하게 함)
import numpy as np

X = np.random.random(10)*10
print('생성된 배열 =',X)

X_mean = X.mean() #평균
print('평균 =',X_mean)

X_std = X.std() #표준편차
print('표준편차 =',X_std)

X_standardization = (X-X_mean)/X_std
print('표준화된 배열 = ', X_standardization)

생성된 배열 = [6.24729415 8.45225205 5.35324143 6.52158455 3.58407784 7.33993569
 6.73117662 5.82790522 5.9350397  5.49479379]
평균 = 6.148730102306941
표준편차 = 1.224729836151643
표준화된 배열 =  [ 0.0804782   1.88084088 -0.64952176  0.30443812 -2.09405551  0.97262723
  0.47557143 -0.26195564 -0.17447963 -0.53394332]


In [15]:
#이론) 비교 연산
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([3,2,5,4,1])

print(A==B) #비교연산의 결과는 항상 bool 타입
print(A==2)

[False  True False  True False]
[False  True False False False]


In [16]:
# 비교 연산 실습과 활용
import numpy as np
A = np.array([1,2,3,4,5])

print('A의 요소중 2보다 크거나 같음을 판별 = ', A>=2)
print('A의 요소중 2보다 크거나 같은것은 몇개? =', sum(A>=2))
print('A의 요소중 2보다 크거나 같은것만 리스트 =', A[A>=2])

A의 요소중 2보다 크거나 같음을 판별 =  [False  True  True  True  True]
A의 요소중 2보다 크거나 같은것은 몇개? = 4
A의 요소중 2보다 크거나 같은것만 리스트 = [2 3 4 5]


In [22]:
#이론) 인덱싱 기초
#1차원
import numpy as np
A =np.array([3,4,1,2,5,3,4])
print(A[0])
print(A[3])
print(A[-7])
print(A[-4])

3
2
3
2


In [23]:
#2차원 이상
import numpy as np
B = np.array([[1,2,3],
             [4,5,6],
            [7,8,9]])
print(B[0])
print(B[0,1])
print(B[1,2])

[1 2 3]
2
6


In [26]:
#이론) 슬라이싱 기초
#1차원
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a[1:5:2])
print(a[1:5])
print(a[1:])
print(a[:])

[1 3]
[1 2 3 4]
[1 2 3 4 5]
[0 1 2 3 4 5]


In [28]:
#2차원
import numpy as np
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])
print(A[1:3, 0:1])
print(A[1:4, 0:2])

[[4]
 [7]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [29]:
#인덱싱과 슬라이싱 실습
import numpy as np 
A = np.array([
	[0, 1, 2],
	[3, 4, 5],
	[6, 7, 8],
	[9, 10, 11]
])

print('1번행만 인덱싱=',A[1])
print('0번행의 2번열 요소 인덱싱=',A[0, 2])
print('1번~4번행전까지 슬라이스, 1번열 요소 인덱싱=',A[1:4, 1])
print('1번~4번행전까지 슬라이스, 0번~2번열전까지 슬라이스=',A[1:4, 0:2])
print('0번행의 요소 역순 슬라이스=',A[0, ::-1])

1번행만 인덱싱= [3 4 5]
0번행의 2번열 요소 인덱싱= 2
1번~4번행전까지 슬라이스, 1번열 요소 인덱싱= [ 4  7 10]
1번~4번행전까지 슬라이스, 0번~2번열전까지 슬라이스= [[ 3  4]
 [ 6  7]
 [ 9 10]]
0번행의 요소 역순 슬라이스= [2 1 0]


In [30]:
#정렬 실습(1/2) 1차원 배열
import numpy as np
a = np.array([4, 1, 2, 5, 0])

print('오름차순 정렬=',np.sort(a))
print('내림차순 정렬=',-np.sort(-a))

오름차순 정렬= [0 1 2 4 5]
내림차순 정렬= [5 4 2 1 0]


In [ ]:
#정렬 실습(2/2) 2차원 배열
import numpy as np	
A = np.array([
	[0, 3, 7],
	[4, 5, 1],
	[2, 6, 9]
])

print('행을 기준으로 오름차순 정렬')
print(np.sort(A, axis = 0))
print('열을 기준으로 오름차순 정렬')
print(np.sort(A, axis = 1))
print('행을 기준으로 내림차순 정렬')
print(-np.sort(-A, axis = 0))
print('열을 기준으로 내림차순 정렬')
print(-np.sort(-A, axis = 1))